In [3]:
from __future__ import print_function
import random 
import sys

sys.setrecursionlimit(1000000)

In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('GALEX_data-extended-feats.csv')

In [6]:
columns = []
count = 0
for col in df.columns:
    if(count == 0):
        label = col
        count += 1
    elif(count<9):
        columns.append(col)
        count += 1
columns.append(label)

In [7]:
columns

['ra', 'dec', 'u', 'g', 'r', 'i', 'z', 'nuv_mag', 'class']

In [8]:
df = df[columns]

In [9]:
df = df.rename(columns={"class":"label"})

In [10]:
columns[-1] = 'label'

In [11]:
df

,ra,dec,u,g,r,i,z,nuv_mag,label
0,184.070888,20.253472,22.557287,21.054333,20.820534,20.792364,20.572094,24.287556,0
1,184.368007,20.716907,23.667465,22.849096,21.240696,19.869997,19.308306,24.398521,1
2,184.285775,20.736396,23.121962,20.563263,18.869553,18.267902,17.888218,23.293421,1
3,183.545455,20.992294,22.300468,20.999990,19.390633,18.621809,18.136063,24.048527,1
4,183.702883,21.154447,22.177027,21.408657,21.410803,21.424093,21.027111,24.103436,2
5,183.469467,21.139612,22.841330,21.124943,19.417271,18.719162,18.323605,23.136250,1
6,183.489113,21.028830,21.995867,20.823610,20.994688,20.947767,20.737692,23.360886,2
7,183.837879,21.013788,20.911606,20.432686,20.289907,20.177324,19.817312,23.002201,2
8,183.287500,20.557827,22.567287,20.677015,18.971281,18.349138,17.995657,23.603683,1
9,184.180088,37.692273,26.119047,22.022085,20.746704,19.892279,19.146225,23.813169,1
10,184.593648,37.940175,24.544317,23.924778,21.349752,20.139803,19.596293,23.830544,1
11,184.428811,38.390015,22.123671,19.650656,18.205114,17.675926,17.304749,24.195551,1
12,186.454245,36.886107,22.484287,21.544075,21.158714,21.349888,21.153795,23.895971,2
13,187.018922,36.942822,21.318008,20.518061,20.195826,19.962152,19.481928,23.514721,2
14,187.124507,36.970319,22.516132,21.742504,20.292412,19.463156,19.062160,23.386084,1
15,186.666231,36.967541,23.808187,21.353825,20.161686,19.362709,19.119766,22.537098,1
16,186.474885,37.017099,20.746429,19.791283,19.517611,19.914310,19.294561,22.817001,0
17,187.031472,37.367018,22.020033,21.151934,19.284315,18.662029,18.231922,23.586870,1
18,187.024936,37.430254,22.672173,22.321838,20.647884,19.813877,19.349596,24.200422,1
19,186.595860,37.460385,20.162193,18.031275,16.976046,16.500900,16.102957,23.017439,1
20,186.540986,37.304213,21.954910,20.896374,19.632917,19.018250,18.673267,23.325781,1
21,186.847449,35.316268,22.235241,21.854801,21.930079,21.663305,22.124161,23.807653,2
22,187.081667,35.364008,21.539555,21.667725,20.539558,19.746792,19.590670,22.252247,1
23,187.623861,35.383432,23.743027,21.523554,21.387028,21.146490,21.191839,24.043781,0
24,186.694101,35.443709,22.554131,21.842695,20.354897,19.503494,19.218468,23.568214,1
25,186.866178,35.744810,25.442774,22.373396,20.769119,19.800301,19.307949,24.102551,1
26,187.878031,35.743402,23.013512,22.148006,20.776201,19.895855,19.505491,22.555792,1
27,187.191710,35.864164,23.721302,21.479513,20.584982,19.673599,19.072708,23.210476,1
28,187.681509,22.515829,23.797625,22.355272,20.711071,19.670860,19.291798,23.591572,1
29,186.947945,22.530091,26.407900,22.093763,21.829588,21.658247,21.854675,24.040236,1
...,...,...,...,...,...,...,...,...,...
8376,191.848293,28.602646,25.781206,22.670904,20.590557,19.500343,19.127462,24.149904,1
8377,192.003557,28.212481,22.260590,21.421566,20.418242,19.552999,19.283684,22.293966,1
8378,192.028097,28.876715,22.557730,20.734831,19.037632,18.439949,18.040371,22.339003,1
8379,192.216499,28.508252,21.318518,20.630541,20.642124,20.608438,20.164667,20.860239,2
8380,192.584633,28.442359,21.018614,20.712805,20.617504,20.422283,20.022245,22.406366,2
8381,193.085505,29.615032,21.713068,21.428288,21.248272,21.281139,21.062315,24.071386,2
8382,193.552654,28.411615,22.484600,21.938990,20.539490,19.462358,19.118643,23.537981,1
8383,193.628264,28.382833,21.979496,20.620388,20.373791,20.445684,20.269903,22.884480,0
8384,193.430307,29.146181,24.008409,21.674299,21.614038,21.789610,22.332840,23.689026,0
8385,193.085505,29.615032,21.713068,21.428288,21.248272,21.281139,21.062315,24.071386,2
8386,192.733036,29.494595,25.305916,21.805450,20.354643,19.239222,18.571117,23.925760,1
8387,192.322859,29.687424,24.017015,21.905329,20.883389,20.105301,19.788834,21.969776,1
8388,191.691557,29.872870,24.897385,21.423967,20.219801,19.504723,19.066156,23.065468,1
8389,191.749322,31.131740,21.198769,20.579073,19.651028,18.950693,18.970509,20.611694,2
8390,192.545995,31.172293,23.196318,22.395283,20.756073,19.651785,19.139799,22.727764,1
8391,192.741266,30.547818,23.635513,21.319847,19.812279,19.055504,18.696108,22.779892,1
8392,192.688716,30.779008,22.444950,19.630739,18.162199,17.648996,17.296913,22.143293,1
8393,193.236881,30.770374,21.680811,19.951628,18.368073,17.862719,17.563824,22.728186,1
8394,190.894154,31.206057,21.464031,20.794106,20.419550,20.445343,20.123053,22.426546,2
8395,190.803460,31.574213,20.420837,19.949741,19.813995,19.790014,19.478338,19.673212,2
8396,191.295153,32.601372,23.227266,21.547089,20.182184,19.401617,19.123924,24.391020,1
8397,179.483483,27.155665,21.850306,20.607334,19.080461,18.376915,18.042477,22.917433,1
8398,177.792868,27.419304,21.728691,21.494640,20.313364,19.371468,18.903740,22.263651,1
8399,177.511094,31.069178,21.166855,20.405647,20.217598,19.846298,19.667187,22.333614,2
8400,178.287163,29.603519,23.928101,21.920706,20.634251,19.878485,19.593121,22.724415,1
8401,177.075371,30.514219,21.324900,19.577299,18.131672,17.528904,17.112585,21.775248,1
8402,177.113986,31.316781,20.511532,20.008595,19.971630,19.931721,19.791796,22.308704,2
8403,177.242527,31.096781,21.528627,20.906515,20.324602,20.121508,19.928530,22.030289,2
8404,177.977195,20.996295,21.819860,21.239298,21.085773,21.145618,20.887722,23.212044,0
8405,182.558651,18.986003,18.339544,17.433079,17.228048,17.184500,17.179554,20.089531,0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8406 entries, 0 to 8405
Data columns (total 9 columns):
ra         8406 non-null float64
dec        8406 non-null float64
u          8406 non-null float64
g          8406 non-null float64
r          8406 non-null float64
i          8406 non-null float64
z          8406 non-null float64
nuv_mag    8406 non-null float64
label      8406 non-null int64
dtypes: float64(8), int64(1)
memory usage: 591.1 KB

In [13]:
def train_test_split(df,test_size):
    if isinstance(test_size,float):
        test_size = round(test_size * len(df))
        
    if(test_size > len(df)):
        return 0, df

    indices = df.index.tolist()
    test_indices = random.sample(population=indices,k = test_size)

    test_df = df.loc[test_indices]
    train_df = df.drop(test_indices)
    
    return train_df, test_df

In [14]:

train_df, test_df = train_test_split(df,0.2)

In [41]:
data = train_df.values

In [42]:
data

array([[184.0708878 ,  20.25347237,  22.55728722, ...,  20.57209396,
         24.28755569,   0.        ],
       [184.3680069 ,  20.71690691,  23.66746521, ...,  19.30830574,
         24.39852142,   1.        ],
       [184.2857749 ,  20.73639638,  23.12196159, ...,  17.88821793,
         23.29342079,   1.        ],
       ...,
       [177.1139859 ,  31.31678132,  20.51153183, ...,  19.79179573,
         22.30870438,   2.        ],
       [177.2425272 ,  31.09678109,  21.5286274 , ...,  19.92852974,
         22.0302887 ,   2.        ],
       [177.9771951 ,  20.99629456,  21.81986046, ...,  20.88772202,
         23.21204376,   0.        ]])

In [43]:
def check_purity(data):
    label_column = data[:,-1]
    unique_classes = np.unique(label_column)

    if(len(unique_classes) == 1):
        return True
    else:
        return False

In [44]:
check_purity(train_df.values)

False

In [45]:
def classify_data(data):
    label_column = data[: , -1]
    unique_classes, counts_unique_classes = np.unique(label_column, return_counts= True)

    index = counts_unique_classes.argmax()
    classification  = unique_classes[index]
    return classification

In [46]:
def get_potential_splits(data):
    potential_splits = {} #Key is indices of the columns
    _ , n_columns = data.shape

    for column_index in range(n_columns-1): #col - 1 because we need to exclude the last col
        potential_splits[column_index] = []
        values = data[:, column_index]
        unique_values = np.unique(values)

        for index in range(len(unique_values)):
            if(index != 0):
                current_value = unique_values[index]
                previous_value = unique_values[index-1]
                potential_split = (current_value + previous_value)/2

                potential_splits[column_index].append(potential_split)
    
    return potential_splits

In [47]:
potential_splits = get_potential_splits(train_df.values)

In [48]:
def split_data(data, split_column, split_value):
    split_column_values = data[:,split_column]

    data_below = data[split_column_values <= split_value]
    data_above = data[split_column_values > split_value]
    
    return data_below, data_above

In [49]:
split_column = 3
split_value = 18.1

In [50]:
data_below, data_above = split_data(data, split_column, split_value)

In [51]:
len(data_below)

811

In [52]:
def calculate_entropy(data):
    label_column = data[:, -1]
    _, counts = np.unique(label_column,return_counts =True)

    probabilities = counts / counts.sum()

    entropy = sum(probabilities * -np.log2(probabilities))

    return entropy

In [53]:
def calculate_overall_entropy(data_below, data_above):
    n_data_points = len(data_below) + len(data_above)

    p_data_below = len(data_below) / n_data_points
    p_data_above = len(data_above) / n_data_points

    overall_entropy = (p_data_below)*calculate_entropy(data_below) + (p_data_above)*calculate_entropy(data_above)

    return overall_entropy

In [54]:
calculate_overall_entropy(data_below,data_above)

1.1732438189205814

In [55]:
calculate_entropy(data_above)

1.288878899189575

In [56]:
def determine_best_split(data, potential_splits):
    overall_entropy = 9999
    best_split_column = 1000
    best_split_value = -1
    for column_index in potential_splits:

        for value in potential_splits[column_index]:
            data_below, data_above = split_data(data,split_column=column_index,split_value=value)
            current_overall_entropy = calculate_overall_entropy(data_below,data_above)

            if current_overall_entropy <= overall_entropy: #PLOT GRAPH AND CHECK FOR BOTH < AND <= CONDITIONS AND CHOOSE THE BETTER ONE
                overall_entropy = current_overall_entropy
                best_split_column = column_index
                best_split_value = value
                
    return best_split_column, best_split_value

In [57]:
potential_splits = get_potential_splits(data)

In [58]:
#determine_best_split(data, potential_splits)

In [59]:
df.values

array([[184.0708878 ,  20.25347237,  22.55728722, ...,  20.57209396,
         24.28755569,   0.        ],
       [184.3680069 ,  20.71690691,  23.66746521, ...,  19.30830574,
         24.39852142,   1.        ],
       [184.2857749 ,  20.73639638,  23.12196159, ...,  17.88821793,
         23.29342079,   1.        ],
       ...,
       [177.2425272 ,  31.09678109,  21.5286274 , ...,  19.92852974,
         22.0302887 ,   2.        ],
       [177.9771951 ,  20.99629456,  21.81986046, ...,  20.88772202,
         23.21204376,   0.        ],
       [182.558651  ,  18.9860032 ,  18.3395443 , ...,  17.17955399,
         20.08953094,   0.        ]])

In [60]:
#sub_tree = {question : [yes_answer, no_answer]}

In [61]:
def decision_tree_algorithm(df, counter=0):
    
    #data preperations
    if(counter == 0):
        data = df.values
    else:
        data = df
        
    #base case
    if(check_purity(data)):
        classification = classify_data(data)
        return classification
    
    #recursive part
    else:
        counter += 1
        #print(counter)
        #helper functions
        
        potential_splits = get_potential_splits(data)
        split_column, split_value = determine_best_split(data,potential_splits)
        
        if(split_value == -1):
            return
        
        data_below, data_above = split_data(data, split_column, split_value)
        
        #instantiate sub-tree
        question = "{} <= {}".format(columns[split_column], split_value)
        sub_tree = {question: []}
        
        #find answers (recursion)
        
        yes_answer = decision_tree_algorithm(data_below, counter)
        no_answer = decision_tree_algorithm(data_above, counter)
        
        if yes_answer == no_answer:
            sub_tree = yes_answer
        else:
            sub_tree[question].append(yes_answer)
            sub_tree[question].append(no_answer)

        return sub_tree

In [62]:
def classify_example(example,tree):
        question = list(tree.keys())[0]
        feature_name, comparison, value = question.split()
        if example[feature_name] <= float(value):
            answer = tree[question][0]
        else:
            answer = tree[question][1]

        if not isinstance(answer,dict):
            return answer

        else:
            answer_tree = answer
            return classify_example(example, answer_tree)

In [63]:
def calculate_accuracy(df, tree):

    df["classification"] = df.apply(classify_example, axis=1, args=(tree,))
    df["classification_correct"] = df["classification"] == df["label"]
    
    accuracy = df["classification_correct"].mean()
    
    return accuracy

In [57]:

train_df2, test_df2 = train_test_split(df,0.2)

In [ ]:
tree2 = decision_tree_algorithm(train_df2)

In [ ]:
calculate_accuracy(test_df2,tree2)

In [ ]:

train_df3,test_df3 = train_test_split(df, 0.3)

In [ ]:
tree3 = decision_tree_algorithm(train_df3)

In [ ]:
calculate_accuracy(test_df3,tree3)

In [ ]:
train_df3

In [190]:

train_df4,test_df4 = train_test_split(df, 0.1)
tree4 = decision_tree_algorithm(train_df4)
calculate_accuracy(test_df4,tree4)

0.8466111771700356

In [ ]:

train_df5,test_df5 = train_test_split(df, 0.5)
tree5 = decision_tree_algorithm(train_df5)
calculate_accuracy(test_df5,tree5)

In [ ]:
tree

In [ ]:
tree2

In [ ]:
tree3

In [ ]:
tree4

In [64]:
def calculate_accuracy_random_forest(df, trees):

    df["classification"] = df.apply(classify_example_random_forest, axis=1, args=(trees,))
    df["classification_correct"] = df["classification"] == df["label"]
    
    accuracy = df["classification_correct"].mean()
    
    return accuracy

In [65]:
def classify_example_random_forest(example,trees):
    count0 = count1 = count2 = 0
    for tree in trees:
        classification =(classify_example(example,tree))
        if(classification == 0):
            count0 += 1
        elif(classification == 1):
            count1 += 1
        elif(classification == 2):
            count2 += 1
    
    label = [count0,count1,count2]
    
    
    fin_class = label.index(max(label))
    return (fin_class)

In [66]:
def random_forest(df,test_size,num_trees):
    total_training_data, test_df = train_test_split(df,test_size)
    training_data = []
    individual_train_data = round(len(total_training_data) / num_trees)
    #print(individual_train_data)
    for i in range(num_trees):
        total_training_data, train_df = train_test_split(total_training_data, individual_train_data)
        
        training_data.append(train_df)
    
    trees = []
    for i in range(num_trees):
        tree = decision_tree_algorithm(training_data[i])
        trees.append(tree)
        
    accuracy = calculate_accuracy_random_forest(test_df, trees)

    #training_data.append(total_training_data)
    return test_df, trees

In [73]:
test_df, trees = random_forest(df,0.2,9)

In [74]:
calculate_accuracy_random_forest(test_df,trees)

0.8709101725163593

In [75]:
tree_accuracy = {}
tree_test_data = {}
for num_trees in range(1,501):
    test_df, trees = random_forest(df,0.2,num_trees)
    accuracy = calculate_accuracy_random_forest(test_df,trees)
    tree_accuracy[num_trees] = accuracy
    tree_test_data[num_trees] = test_df
    print(num_trees,' : ', accuracy)

1  :  0.8643664485425342
2  :  0.8405710886377157
3  :  0.8720999405116002
4  :  0.8720999405116002
5  :  0.8720999405116002
6  :  0.8673408685306365
7  :  0.8786436644854253
8  :  0.8792385484830458
9  :  0.883402736466389
10  :  0.8703152885187388
11  :  0.8822129684711482
12  :  0.8536585365853658
13  :  0.8625817965496728
14  :  0.8572278405710886
15  :  0.8685306365258775
16  :  0.8822129684711482
17  :  0.8661511005353956
18  :  0.8655562165377751
19  :  0.8685306365258775
20  :  0.8655562165377751
21  :  0.8602022605591909
22  :  0.8572278405710886
23  :  0.8697204045211184
24  :  0.8607971445568114
25  :  0.8732897085068412
26  :  0.8590124925639501
27  :  0.8786436644854253
28  :  0.8715050565139798
29  :  0.8607971445568114
30  :  0.8584176085663295
31  :  0.8792385484830458
32  :  0.8625817965496728
33  :  0.8661511005353956
34  :  0.8560380725758477
35  :  0.8447352766210589
36  :  0.8572278405710886
37  :  0.8536585365853658
38  :  0.8703152885187388
39  :  0.8536585365853658
40  :  0.8661511005353956
41  :  0.843545508625818
42  :  0.8500892325996431
43  :  0.8566329565734682
44  :  0.8596073765615705
45  :  0.8619869125520524
46  :  0.8417608566329565
47  :  0.8566329565734682
48  :  0.8548483045806068
49  :  0.8530636525877454
50  :  0.8494943486020226
51  :  0.8375966686496134
52  :  0.8488994646044021
53  :  0.8441403926234384
54  :  0.8560380725758477
55  :  0.8530636525877454
56  :  0.8459250446162998
57  :  0.8441403926234384
58  :  0.8500892325996431
59  :  0.8465199286139203
60  :  0.8530636525877454
61  :  0.843545508625818
62  :  0.8477096966091612
63  :  0.8393813206424747
64  :  0.8334324806662701
65  :  0.8465199286139203
66  :  0.8560380725758477
67  :  0.8393813206424747
68  :  0.8471148126115408
69  :  0.8524687685901249
70  :  0.8488994646044021
71  :  0.8399762046400951
72  :  0.8542534205829864
73  :  0.8399762046400951
74  :  0.8370017846519928
75  :  0.8364069006543724
76  :  0.8405710886377157
77  :  0.8483045806067817
78  :  0.8429506246281975
79  :  0.8441403926234384
80  :  0.8560380725758477
81  :  0.8554431885782272
82  :  0.8322427126710291
83  :  0.8381915526472338
84  :  0.825698988697204
85  :  0.8310529446757883
86  :  0.8459250446162998
87  :  0.8310529446757883
88  :  0.8262938726948245
89  :  0.819155264723379
90  :  0.8334324806662701
91  :  0.8340273646638905
92  :  0.8334324806662701
93  :  0.828078524687686
94  :  0.8381915526472338
95  :  0.843545508625818
96  :  0.8245092207019631
97  :  0.8393813206424747
98  :  0.834622248661511
99  :  0.8340273646638905
100  :  0.8453301606186794
101  :  0.8625817965496728
102  :  0.8471148126115408
103  :  0.8381915526472338
104  :  0.8292682926829268
105  :  0.8494943486020226
106  :  0.817965496728138
107  :  0.8239143367043427
108  :  0.8447352766210589
109  :  0.8310529446757883
110  :  0.8316478286734087
111  :  0.8417608566329565
112  :  0.8274836406900654
113  :  0.8518738845925045
114  :  0.8328375966686496
115  :  0.8393813206424747
116  :  0.8328375966686496
117  :  0.8393813206424747
118  :  0.8417608566329565

TypeError: object of type 'int' has no len()

In [1]:
tree_accuracy

NameError: name 'tree_accuracy' is not defined

In [90]:
example = test_df.iloc[4]
classify_example_random_forest(example,trees)

1

In [91]:
1 == 1.0

True

In [92]:
def calculate_accuracy_random_forest(df, trees):

    df["classification"] = df.apply(classify_example_random_forest, axis=1, args=(trees,))
    df["classification_correct"] = df["classification"] == df["label"]
    
    accuracy = df["classification_correct"].mean()
    
    return accuracy

In [93]:
calculate_accuracy_random_forest(test_df,trees)

0.8958953004164188